all:	
	#g++ motor_test.cpp ../src/JHPWMPCA9685.cpp -I ../src -o ../build/motor_test -O2 -larmadillo
	# g++ limited_inverse.cpp -o lim -O2 -larmadillo 
	#g++ jacobian_inverse.cpp -o jac -O2 -larmadillo
	g++ jacobian_inverse.cpp  ../src/JHPWMPCA9685.cpp -I ../src -o jac -O2 -larmadillo
	#g++ motor_interface_control.cpp -o mic -O2 -larmadillo

